move publisher and subscriber get_keyexpr implementation from impl.hxx to api.hxx
eclipse-zenoh/zenoh-cpp pull request #87
Opened 2023-12-12 15:34 UTC by lucasw

I haven't tested much but this appears to solve the linker issue in https://github.com/eclipse-zenoh/roadmap/discussions/105

All the other get_keyexpr() implementations were already in api.hxx and not impl.hxx, so this matches this pattern (but maybe not the intent of the api-impl split).

2023-12-14 17:58 UTC, lucasw commented
I've added a very minimal example running in the github action that is built in CI (but possibly you don't want that as a part of CI feel free to change it or remove it), and there's another branch without the moved key_expr that demonstrates the issue: https://github.com/lucasw/zenoh-cpp/actions?query=branch%3Amultiple_declaration_ci++ - [a specific example](https://github.com/lucasw/zenoh-cpp/actions/runs/7212669338/job/19650842520#step:6:35)

2023-12-16 10:29 UTC, Mallets commented
Thanks @lucasw for your PR. We will have a look at it as soon as possible.

2023-12-19 08:11 UTC, milyin requested changes
The fix for missing inline is very important and should be integrated before release. But change in example is not directly related to this missing inline fix and need to be adjusted to existing 'simple' example (btw I like the idea to rename them to 'standalone', this better reflects the purpose)
I'm going to make separate PR with fix for `inline` issue only.
Later need to make systematic test for this issue: https://github.com/eclipse-zenoh/zenoh-cpp/issues/55

2023-12-19 08:11 UTC, milyin commented on examples/standalone/foo.cpp
Not sure what's the purpose of this additional .cpp file? Also all other files in project have .cxx extension

2023-12-19 08:11 UTC, milyin commented on examples/standalone/CMakeLists.txt
This mostly repeats functionality of tests https://github.com/eclipse-zenoh/zenoh-cpp/tree/main/examples/simple
Though I like the name 'standalone' and agree that example in 'simple' can be made a bit more simple

2023-12-19 08:46 UTC, milyin commented on examples/standalone/foo.cpp
A, ok, I see, that's to test the linker error on multiple include. Anyway better to mention this explicitly and do this in tests instead of examples.

2023-12-21 10:37 UTC, milyin commented
Bug fixed in separate PR https://github.com/eclipse-zenoh/zenoh-cpp/issues/55, thank you @lucasw 
The validation that no inlines are forgotten should be done in tests, this will close issue https://github.com/eclipse-zenoh/zenoh-cpp/issues/55
The update to simple examples is also good idea, added task to not forget it https://github.com/eclipse-zenoh/zenoh-cpp/issues/92

2023-12-21 10:37 UTC, closed without merging